# Generated by Django 5.2.7 on 2025-10-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('link', models.CharField()),
                ('id', models.CharField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
